query IndexRouteQuery($profileId: UUID!, $after: Cursor) {
	feed: postCollection(orderBy: [{ voteRank: AscNullsFirst }], first: 15, after: $after) {
		pageInfo {
			hasNextPage
			endCursor
		}
		edges {
			cursor
			node {
				id
				...FeedItem_PostFragment
			}
		}
	}
}
