name: ci
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 16
      - run: yarn codegen
      - run: yarn workspace app run build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: the-guild-org/shared-config/setup@main
        with:
          nodeVersion: 16
      - run: yarn workspace app run lint
